name: Laravel/Lumen CI/CD
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  web-deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.3.3'
      - uses: actions/checkout@v2.3.2
      - name: Directory Permissions
        run: chmod -R 775 storage
      - name: Install Dependencies
        run: composer update --ignore-platform-reqs
      - name: clear cache
        run: php artisan optimizer:clear
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: ./ci-cd-test.shakilahmeed.com/
