- name: 'Deploy to UAT'
  uses: januszmarcinik/ftp-deploy@v1
  with:
    server: ${{ secrets.SERVER }}
    user: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    # localRoot: web/dist